image: node:latest

stages:
  - build
  - test

before_script:
  - yarn install

build cogito:
  stage: build
  script:
    - yarn lerna run --scope @cogitojs/** build
  cache:
    untracked: true

test javascript:
  stage: test
  script:
    - yarn test

test cogito-ios-app:
  stage: test
  variables:
    BUNDLE_GEMFILE: .ruby-dependencies/Gemfile
  before_script:
    - cd workspaces/cogito-ios-app
    - bundle install
  script:
    - bundle exec fastlane tests
    - bundle exec slather coverage
  tags:
    - ios

test telepath-ios:
  stage: test
  variables:
    BUNDLE_GEMFILE: .ruby-dependencies/Gemfile
  before_script:
    - cd workspaces/telepath-ios
    - bundle install
  script:
    - bundle exec fastlane tests
    - bundle exec slather coverage
  tags:
    - ios
