image: node:9.4.0

stages:
  - test
  - build
  - publish

before_script:
  - yarn install

test javascript:
  stage: test
  script:
    - yarn test

test cogito-ios-app:
  stage: test
  variables:
    BUNDLE_GEMFILE: .ruby-dependencies/Gemfile
  before_script:
    - cd packages/cogito-ios-app
    - bundle install
  script:
    - bundle exec fastlane tests
    - bundle exec slather coverage
  tags:
    - ios

test telepath-ios:
  stage: test
  variables:
    BUNDLE_GEMFILE: .ruby-dependencies/Gemfile
  before_script:
    - cd packages/telepath-ios
    - bundle install
  script:
    - bundle exec fastlane tests
    - bundle exec slather coverage
  tags:
    - ios

build cogito-web3:
  stage: build
  script:
    - yarn lerna run --scope @cogito/cogito-web3 build
  artifacts:
    paths:
      - packages/cogito-web3/es/
      - packages/cogito-web3/lib/
      - packages/cogito-web3/umd/

build telepath-js:
  stage: build
  script:
    - yarn lerna run --scope @cogito/telepath-js build
  artifacts:
    paths:
      - packages/telepath-js/es/
      - packages/telepath-js/lib/
      - packages/telepath-js/umd/

publish cogito-web3:
  stage: publish
  script:
    - echo $ARTIFACTORY_DOTNPMRC_PART >> .npmrc
    - yarn lerna publish --scope @cogito/cogito-web3 --skip-git --npm-tag=$CI_COMMIT_TAG --force-publish=*
  only:
    - tags

publish telepath-js:
  stage: publish
  script:
    - echo $ARTIFACTORY_DOTNPMRC_PART >> .npmrc
    - yarn lerna publish --scope @cogito/telepath-js --skip-git --npm-tag=$CI_COMMIT_TAG --force-publish=*
  only:
    - tags
