stages:
  - build

build_project:
  stage: build
  before_script:
    - bundle install --gemfile=.ruby-dependencies/Gemfile
  script:
    - xcodebuild build test -workspace Telepath.xcworkspace -scheme TelepathTests -destination 'platform=iOS Simulator,name=iPhone X,OS=11.1' | xcpretty
  after_script:
    - BUNDLE_GEMFILE=.ruby-dependencies/Gemfile bundle exec slather coverage
  tags:
    - ppf-cios
