image: node:9.11.1

stages:
  - build
  - test
  - deploy

build cogito:
  stage: build
  before_script:
    - yarn install
  script:
    - yarn lerna run --scope @cogitojs/** build
    - cd workspaces/demo-app/truffle && yarn install && yarn truffle compile
  cache:
    untracked: true

test javascript:
  stage: test
  script:
    - yarn test
    - cd workspaces/demo-app/truffle && yarn test
  cache:
    untracked: true

test cogito-ios-app:
  stage: test
  variables:
    BUNDLE_GEMFILE: .ruby-dependencies/Gemfile
  before_script:
    - cd workspaces/cogito-ios-app
    - bundle install
  script:
    - bundle exec fastlane tests
    - bundle exec slather coverage
  tags:
    - ios

test telepath-ios:
  stage: test
  variables:
    BUNDLE_GEMFILE: .ruby-dependencies/Gemfile
  before_script:
    - cd workspaces/telepath-ios
    - bundle install
  script:
    - bundle exec fastlane tests
    - bundle exec slather coverage
  tags:
    - ios

test cogito-attestations-ios:
  stage: test
  variables:
    BUNDLE_GEMFILE: .ruby-dependencies/Gemfile
  before_script:
    - brew install yarn || brew upgrade yarn
    - yarn install
    - yarn build
    - cd workspaces/cogito-attestations-ios
    - bundle install
  script:
    - bundle exec fastlane tests
    - bundle exec slather coverage
  tags:
    - ios

deploy faucet:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  variables:
    TMP_IMAGE_TAG: faucet
    AWS_REPOSITORY_URL: 212699287803.dkr.ecr.eu-central-1.amazonaws.com/blockchainlab
  before_script:
    - cd workspaces/faucet
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - $(aws ecr get-login --no-include-email --region eu-central-1)
  script:
    - cd workspaces/faucet
    - docker build -t $TMP_IMAGE_TAG .
    - docker tag $TMP_IMAGE_TAG $AWS_REPOSITORY_URL:$TMP_IMAGE_TAG-latest
    - docker push $AWS_REPOSITORY_URL:$TMP_IMAGE_TAG-latest
    - docker tag $TMP_IMAGE_TAG $AWS_REPOSITORY_URL:$TMP_IMAGE_TAG-$CI_COMMIT_TAG
    - docker push $AWS_REPOSITORY_URL:$TMP_IMAGE_TAG-$CI_COMMIT_TAG
  only:
    - tags
