image: node:9.4.0

stages:
  - test
  - build

before_script:
  - yarn install

test cogito-web3:
  stage: test
  script:
    - yarn test

test telepath-queuing-service:
  stage: test
  script:
    - cd packages/telepath-queuing-service
    - yarn test

test cogito-ios-app:
  stage: test
  script:
    - cd packages/cogito-ios-app
    - fastlane tests
  tags:
    - ppf-cios

build cogito-web3:
  stage: build
  script:
    - yarn lerna run --scope @cogito/cogito-web3 build
  cache:
    paths:
      - node_modules/
      - packages/cogito-web3/node_modules/

build telepath-js:
  stage: build
  script:
    - yarn lerna run --scope @cogito/telepath-js build
  allow_failure: true
  cache:
    paths:
      - node_modules/
      - packages/telepath-js/node_modules/
