image: node:9.11.1

stages:
  - build
  - test

build cogito:
  stage: build
  before_script:
    - yarn install
    - cd workspaces/demo-app/truffle && yarn install
  script:
    - yarn lerna run --scope @cogitojs/** build
    - cd workspaces/demo-app/truffle && yarn truffle compile
  cache:
    untracked: true

test javascript:
  stage: test
  script:
    - yarn test
  cache:
    untracked: true

test cogito-ios-app:
  stage: test
  variables:
    BUNDLE_GEMFILE: .ruby-dependencies/Gemfile
  before_script:
    - cd workspaces/cogito-ios-app
    - bundle install
  script:
    - bundle exec fastlane tests
    - bundle exec slather coverage
  tags:
    - ios

test telepath-ios:
  stage: test
  variables:
    BUNDLE_GEMFILE: .ruby-dependencies/Gemfile
  before_script:
    - cd workspaces/telepath-ios
    - bundle install
  script:
    - bundle exec fastlane tests
    - bundle exec slather coverage
  tags:
    - ios
