image: node:9.4.0

stages:
  - test
  - build
  - publish

before_script:
  - yarn install

test javascript:
  stage: test
  script:
    - yarn test

test cogito-ios-app:
  stage: test
  variables:
    BUNDLE_GEMFILE: .ruby-dependencies/Gemfile
  before_script:
    - cd packages/cogito-ios-app
    - bundle install
  script:
    - bundle exec fastlane tests
    - bundle exec slather coverage
  tags:
    - ios

test telepath-ios:
  stage: test
  variables:
    BUNDLE_GEMFILE: .ruby-dependencies/Gemfile
  before_script:
    - cd packages/telepath-ios
    - bundle install
  script:
    - bundle exec fastlane tests
    - bundle exec slather coverage
  tags:
    - ios

build cogito-web3:
  stage: build
  script:
    - yarn lerna run --scope @cogito/cogito-web3 build
  cache:
    paths:
      - node_modules/
      - packages/cogito-web3/node_modules/

build telepath-js:
  stage: build
  script:
    - yarn lerna run --scope @cogito/telepath-js build
  allow_failure: true
  cache:
    paths:
      - node_modules/
      - packages/telepath-js/node_modules/

publish telepath-js:
  stage: publish
  script:
    - echo $ARTIFACTORY_DOTNPMRC_PART >> .npmrc
    - yarn lerna publish --scope @cogito/telepath-js
