stages:
  - build

build_project:
  stage: build
  before_script:
    - bundle install --gemfile=.doesntworkinprojectroot/Gemfile
  script:
    - xcodebuild build test -workspace Cogito.xcworkspace -scheme CogitoTests -destination 'platform=iOS Simulator,name=iPhone X,OS=11.2' | xcpretty
  after_script:
    - BUNDLE_GEMFILE=.doesntworkinprojectroot/Gemfile bundle exec slather coverage
  tags:
    - ppf-cios
