image: node:9.4.0

stages:
  - test
  - build

test:  
  stage: test
  script:
    - yarn && (cd truffle && yarn && yarn test)
    - CI=TRUE yarn test
  tags:
    - docker

build:
  stage: build
  script:
    - (cd truffle && yarn && yarn truffle compile --network dsp)
    - yarn && yarn build
  tags:
    - docker
cache:
  paths:
    - node_modules/
    - truffle/node_modules/
